import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import { SettingsState } from "../../types/settings";
import { DbRoleCode } from "../../types/tenant";
import { SystemRole, AppView } from "../../types/common";

const initialSettingsState: SettingsState = {
    appName: 'Enterprise Manager',
    logoUrl: '',
    primaryColor: '#4f46e5',
    enabledModules: { pos: true, inventory: true, finance: true, labor: true, purchases: true, sales: true, daily: true, storefront: true },
    rolePermissions: {
        [DbRoleCode.OWNER]: [
            // Main Groups
            'DASHBOARD', 'PROFIT_PULSE', 'SALES', 'PURCHASE', 'CUSTOMERS', 'SUPPLIERS',
            'INVENTORY', 'FINANCE', 'POS', 'EXPENSES', 'REPORTS', 'UTILITIES', 'SETTINGS',
            'GROW', 'LABOR', 'STAFF_MANAGER', 'PAYROLL', 'ATTENDANCE_SUMMARY', 'ATTENDANCE_BOARD', 'ALLOWANCE_MANAGER',

            // Dashboard
            'DASHBOARD_OVERVIEW', 'DASHBOARD_SNAPSHOT', 'DASHBOARD_SUMMARY',

            // Sales
            'SALES_REGISTER', 'SALES_INVOICE', 'ESTIMATE', 'SALES_ORDER', 'DELIVERY_CHALLAN',
            'SALES_RETURN', 'PAYMENT_IN', 'CUSTOMER_CREDITS', 'OUTSTANDING_DUES',
            'CHALLAN_LIST', 'PAYMENT_IN_LIST', 'INVOICE_REGISTER', 'ORDER_REGISTER', 'RETURNED_ITEMS',

            // Purchases
            'PURCHASE_REGISTER', 'PURCHASE_ENTRY', 'PURCHASE_ORDER', 'GOODS_RECEIVED',
            'DEBIT_NOTES', 'SUPPLIER_PAYMENTS', 'OUTSTANDING_PAYABLES', 'VENDOR_INFLOW_OUTFLOW',

            // Customers
            'CUSTOMER_LIST', 'CUSTOMER_LEDGER', 'CUSTOMER_STATEMENTS', 'CUSTOMER_GROUPS', 'LOYALTY_POINTS',

            // Suppliers
            'SUPPLIER_LIST', 'SUPPLIER_LEDGER', 'SUPPLIER_STATEMENTS', 'SUPPLIER_GROUPS', 'VENDORS', 'VENDOR_DETAILS', 'VENDOR_FORM',

            // Inventory
            'INVENTORY_ITEMS', 'ITEM_CATEGORIES', 'STOCK_SUMMARY', 'STOCK_MOVEMENT',
            'LOW_STOCK_ALERTS', 'UNITS_HSN', 'WAREHOUSES', 'BATCH_EXPIRY', 'AGED_STOCK',

            // Finance (Cash & Bank)
            'CASH_ACCOUNTS', 'BANK_ACCOUNTS', 'PETTY_CASH', 'FUND_TRANSFERS', 'BANK_RECONCILIATION', 'BANK_STATEMENT', 'LOAN_ACCOUNTS',

            // POS
            'POS_ORDERS', 'POS_RETURNS', 'SHIFT_MANAGEMENT', 'CASH_DRAWER',

            // Expenses
            'EXPENSE_CATEGORIES', 'RECURRING_EXPENSES', 'EXPENSE_REPORTS',

            // Reports
            'REPORT_SALES', 'REPORT_PURCHASE', 'REPORT_INVENTORY', 'REPORT_CUSTOMER',
            'REPORT_SUPPLIER', 'REPORT_TAX', 'REPORT_FINANCIAL', 'DAY_BOOK', 'TRIAL_BALANCE',
            'PROFIT_LOSS', 'BALANCE_SHEET', 'CASH_FLOW',

            // Utilities
            'BARCODE_GENERATOR', 'LABEL_PRINTING', 'BULK_IMPORT', 'DATA_EXPORT', 'NUMBER_SERIES', 'AUDIT_LOGS', 'BARCODE',

            // Settings
            'BUSINESS_PROFILE', 'TAX_CONFIGURATION', 'INVOICE_SETTINGS', 'USERS_ROLES',
            'BRANCH_SETTINGS', 'FINANCIAL_YEAR', 'INTEGRATIONS', 'BACKUP_RESTORE', 'THEMES_BRANDING', 'STOREFRONT',

            // Grow Platform
            'GROW_DASHBOARD', 'GROW_OVERVIEW', 'GROW_PERFORMANCE', 'GROW_MARKETING_METRICS',
            'GROW_STORE', 'GROW_STORE_SETUP', 'GROW_PRODUCT_SYNC', 'GROW_STORE_ORDERS', 'GROW_STORE_CUSTOMERS', 'GROW_STORE_PAYMENTS', 'GROW_STORE_THEMES', 'GROW_STORE_DOMAIN', 'GROW_STORE_SHIPPING',
            'GROW_MARKETING', 'GROW_MARKETING_CAMPAIGNS', 'GROW_MARKETING_TEMPLATES', 'GROW_MARKETING_EMAIL', 'GROW_MARKETING_WHATSAPP', 'GROW_MARKETING_SOCIAL', 'GROW_MARKETING_COUPONS', 'GROW_MARKETING_OFFERS',
            'GROW_GOOGLE', 'GROW_GOOGLE_PROFILE', 'GROW_GOOGLE_REVIEWS', 'GROW_GOOGLE_POSTS', 'GROW_GOOGLE_INSIGHTS', 'GROW_GOOGLE_PHOTOS',
            'GROW_ENGAGEMENT', 'GROW_ENGAGEMENT_SMS', 'GROW_ENGAGEMENT_WHATSAPP', 'GROW_ENGAGEMENT_EMAIL', 'GROW_ENGAGEMENT_LOYALTY', 'GROW_ENGAGEMENT_FEEDBACK',
            'GROW_SYNC', 'GROW_SYNC_DEVICE', 'GROW_SYNC_CLOUD', 'GROW_BACKUP', 'GROW_RESTORE_DATA', 'GROW_SYNC_LOGS', 'SYNC_SHARE', 'RESTORE',
            'GROW_DATA', 'GROW_DATA_IMPORT', 'GROW_DATA_EXPORT', 'GROW_DATA_CLEANUP', 'GROW_DATA_DUPLICATES', 'GROW_DATA_HEALTH',
            'GROW_REPORTS', 'GROW_REPORT_SALES', 'GROW_REPORT_ROI', 'GROW_REPORT_CUSTOMER', 'GROW_REPORT_TRAFFIC', 'GROW_REPORT_CONVERSION', 'GROW_SUPER_ADMIN_CONSOLE', 'GROW_TENANT_CONFIG', 'TENANT_MANAGEMENT'
        ],
        [DbRoleCode.CO_OWNER]: [
            // Dashboard
            'DASHBOARD', 'PROFIT_PULSE', 'DASHBOARD_OVERVIEW', 'DASHBOARD_SNAPSHOT', 'DASHBOARD_SUMMARY',

            // Employee Management (HR)
            'HR', 'LABOR', 'STAFF_MANAGER', 'PAYROLL', 'ATTENDANCE_SUMMARY', 'ATTENDANCE_BOARD', 'ALLOWANCE_MANAGER',

            // Purchase
            'PURCHASE', 'PURCHASE_REGISTER', 'PURCHASE_ENTRY', 'PURCHASE_ORDER', 'GOODS_RECEIVED',
            'DEBIT_NOTES', 'SUPPLIER_PAYMENTS', 'OUTSTANDING_PAYABLES', 'VENDOR_INFLOW_OUTFLOW',
            'PURCHASE_BILLS', 'BILL_FORM', 'PURCHASE_PAYMENT_OUT', 'PURCHASE_HISTORY', 'PURCHASE_ORDER_DETAILS',
            'PURCHASE_ORDER_FORM', 'PURCHASE_ORDER_LIST', 'PURCHASE_RETURN', 'PURCHASE_RETURNS', 'PURCHASE_RETURN_FORM',
            'PURCHASE_UPLOAD', 'RATE_REVISIONS', 'CHEQUES_VAULT', 'SUPPLIER_AGEING',

            // Vendor Management
            'SUPPLIERS', 'SUPPLIER_LIST', 'SUPPLIER_LEDGER', 'SUPPLIER_STATEMENTS', 'SUPPLIER_GROUPS',
            'VENDORS', 'VENDOR_DETAILS', 'VENDOR_FORM',

            // Finance (Cash & Bank)
            'FINANCE', 'CASH_ACCOUNTS', 'BANK_ACCOUNTS', 'PETTY_CASH', 'FUND_TRANSFERS', 'BANK_RECONCILIATION', 'BANK_STATEMENT', 'LOAN_ACCOUNTS'
        ],
        [DbRoleCode.ADMIN]: [
            // Main Groups
            'DASHBOARD', 'PROFIT_PULSE', 'SALES', 'PURCHASE', 'CUSTOMERS', 'SUPPLIERS',
            'INVENTORY', 'FINANCE', 'POS', 'EXPENSES', 'REPORTS', 'UTILITIES', 'SETTINGS',
            'GROW', 'LABOR', 'STAFF_MANAGER', 'PAYROLL', 'ATTENDANCE_SUMMARY', 'ATTENDANCE_BOARD',

            // Dashboard
            'DASHBOARD_OVERVIEW', 'DASHBOARD_SNAPSHOT', 'DASHBOARD_SUMMARY',

            // Sales
            'SALES_REGISTER', 'SALES_INVOICE', 'ESTIMATE', 'SALES_ORDER', 'DELIVERY_CHALLAN',
            'SALES_RETURN', 'PAYMENT_IN', 'CUSTOMER_CREDITS', 'OUTSTANDING_DUES',
            'CHALLAN_LIST', 'PAYMENT_IN_LIST', 'INVOICE_REGISTER', 'ORDER_REGISTER', 'RETURNED_ITEMS',

            // Purchases
            'PURCHASE_REGISTER', 'PURCHASE_ENTRY', 'PURCHASE_ORDER', 'GOODS_RECEIVED',
            'DEBIT_NOTES', 'SUPPLIER_PAYMENTS', 'OUTSTANDING_PAYABLES', 'VENDOR_INFLOW_OUTFLOW',

            // Customers
            'CUSTOMER_LIST', 'CUSTOMER_LEDGER', 'CUSTOMER_STATEMENTS', 'CUSTOMER_GROUPS', 'LOYALTY_POINTS',

            // Suppliers
            'SUPPLIER_LIST', 'SUPPLIER_LEDGER', 'SUPPLIER_STATEMENTS', 'SUPPLIER_GROUPS', 'VENDORS', 'VENDOR_DETAILS', 'VENDOR_FORM',

            // Inventory
            'INVENTORY_ITEMS', 'ITEM_CATEGORIES', 'STOCK_SUMMARY', 'STOCK_MOVEMENT',
            'LOW_STOCK_ALERTS', 'UNITS_HSN', 'WAREHOUSES', 'BATCH_EXPIRY', 'AGED_STOCK',

            // Finance (Cash & Bank)
            'CASH_ACCOUNTS', 'BANK_ACCOUNTS', 'PETTY_CASH', 'FUND_TRANSFERS', 'BANK_RECONCILIATION', 'BANK_STATEMENT', 'LOAN_ACCOUNTS',

            // POS
            'POS_ORDERS', 'POS_RETURNS', 'SHIFT_MANAGEMENT', 'CASH_DRAWER',

            // Expenses
            'EXPENSE_CATEGORIES', 'RECURRING_EXPENSES', 'EXPENSE_REPORTS',

            // Reports
            'REPORT_SALES', 'REPORT_PURCHASE', 'REPORT_INVENTORY', 'REPORT_CUSTOMER',
            'REPORT_SUPPLIER', 'REPORT_TAX', 'REPORT_FINANCIAL', 'DAY_BOOK', 'TRIAL_BALANCE',
            'PROFIT_LOSS', 'BALANCE_SHEET', 'CASH_FLOW',

            // Utilities
            'BARCODE_GENERATOR', 'LABEL_PRINTING', 'BULK_IMPORT', 'DATA_EXPORT', 'NUMBER_SERIES', 'AUDIT_LOGS', 'BARCODE',

            // Settings
            'BUSINESS_PROFILE', 'TAX_CONFIGURATION', 'INVOICE_SETTINGS', 'USERS_ROLES',
            'BRANCH_SETTINGS', 'FINANCIAL_YEAR', 'INTEGRATIONS', 'BACKUP_RESTORE', 'THEMES_BRANDING', 'STOREFRONT',

            // Grow Platform
            'GROW_DASHBOARD', 'GROW_OVERVIEW', 'GROW_PERFORMANCE', 'GROW_MARKETING_METRICS',
            'GROW_STORE', 'GROW_STORE_SETUP', 'GROW_PRODUCT_SYNC', 'GROW_STORE_ORDERS', 'GROW_STORE_CUSTOMERS', 'GROW_STORE_PAYMENTS', 'GROW_STORE_THEMES', 'GROW_STORE_DOMAIN', 'GROW_STORE_SHIPPING',
            'GROW_MARKETING', 'GROW_MARKETING_CAMPAIGNS', 'GROW_MARKETING_TEMPLATES', 'GROW_MARKETING_EMAIL', 'GROW_MARKETING_WHATSAPP', 'GROW_MARKETING_SOCIAL', 'GROW_MARKETING_COUPONS', 'GROW_MARKETING_OFFERS',
            'GROW_GOOGLE', 'GROW_GOOGLE_PROFILE', 'GROW_GOOGLE_REVIEWS', 'GROW_GOOGLE_POSTS', 'GROW_GOOGLE_INSIGHTS', 'GROW_GOOGLE_PHOTOS',
            'GROW_ENGAGEMENT', 'GROW_ENGAGEMENT_SMS', 'GROW_ENGAGEMENT_WHATSAPP', 'GROW_ENGAGEMENT_EMAIL', 'GROW_ENGAGEMENT_LOYALTY', 'GROW_ENGAGEMENT_FEEDBACK',
            'GROW_SYNC', 'GROW_SYNC_DEVICE', 'GROW_SYNC_CLOUD', 'GROW_BACKUP', 'GROW_RESTORE_DATA', 'GROW_SYNC_LOGS', 'SYNC_SHARE', 'RESTORE',
            'GROW_DATA', 'GROW_DATA_IMPORT', 'GROW_DATA_EXPORT', 'GROW_DATA_CLEANUP', 'GROW_DATA_DUPLICATES', 'GROW_DATA_HEALTH',
            'GROW_REPORTS', 'GROW_REPORT_SALES', 'GROW_REPORT_ROI', 'GROW_REPORT_CUSTOMER', 'GROW_REPORT_TRAFFIC', 'GROW_REPORT_CONVERSION', 'GROW_SUPER_ADMIN_CONSOLE', 'GROW_TENANT_CONFIG', 'TENANT_MANAGEMENT'
        ],
        [DbRoleCode.MANAGER]: ['DASHBOARD', 'PROFIT_PULSE', 'POS', 'INVENTORY', 'PURCHASE', 'VENDORS', 'VENDOR_FORM', 'AGED_STOCK', 'FINANCE', 'CASH_ACCOUNTS', 'BANK_ACCOUNTS', 'PETTY_CASH', 'FUND_TRANSFERS', 'SALES', 'DAILY', 'LABOR', 'STOREFRONT', 'REPORTS', 'SYNC_SHARE', 'BARCODE', 'DATA_EXPORT', 'SALES_INVOICE', 'SALES_ORDER', 'ESTIMATE', 'DELIVERY_CHALLAN', 'PAYMENT_IN', 'PAYMENT_IN_LIST', 'SALES_RETURN', 'RETURNED_ITEMS', 'INVOICE_REGISTER', 'ORDER_REGISTER', 'PURCHASE_ENTRY', 'EXPENSES', 'PURCHASE_ORDER', 'GROW_SYNC', 'GROW_DATA', 'GROW_REPORTS'],
        [DbRoleCode.STAFF]: [
            'DASHBOARD', 'POS', 'SALES', 'DAILY', 'STOREFRONT', 'INVENTORY', 'PURCHASE', 'CUSTOMERS', 'SUPPLIERS', 'HR',
            'SALES_INVOICE', 'PAYMENT_IN', 'PURCHASE_ORDER', 'STAFF_MANAGER', 'LABOR', 'EXPENSES', 'REPORTS',
            'POS_ORDERS', 'POS_RETURNS', 'SHIFT_MANAGEMENT', 'CASH_DRAWER',
            'SALES_REGISTER', 'SALES_ORDER', 'ESTIMATE', 'DELIVERY_CHALLAN', 'SALES_RETURN',
            'CUSTOMER_LIST', 'SUPPLIER_LIST', 'INVENTORY_ITEMS', 'ITEM_CATEGORIES', 'STOCK_SUMMARY'
        ]
    },
    defaultTaxMode: 'INCLUSIVE',
    expiryRules: {
        criticalDays: 30,
        criticalDiscount: 50,
        highDays: 60,
        highDiscount: 30,
        mediumDays: 90,
        mediumDiscount: 15
    }
};

const settingsSlice = createSlice({
    name: 'settings',
    initialState: initialSettingsState,
    reducers: {
        updateSettings: (state, action: PayloadAction<Partial<SettingsState>>) => {
            return { ...state, ...action.payload };
        },
        updateRolePermissions: (state, action: PayloadAction<{ role: SystemRole | string, views: AppView[] }>) => {
            const roleKey = action.payload.role.toLowerCase() as DbRoleCode;
            state.rolePermissions[roleKey] = action.payload.views;
        },
        resetSettings: () => initialSettingsState
    }
});

export const { updateSettings, updateRolePermissions, resetSettings } = settingsSlice.actions;
export const settingsReducer = settingsSlice.reducer;
export default settingsSlice.reducer;
