import express from "express";
import { getSyncConfig, updateSettings, getDevices, addDevice, getBackups, triggerBackup, restoreBackup, getConflicts } from "../controllers/SyncController.js";
import { protect } from '@smarterp/shared/middlewares/authMiddleware.js';
const router = express.Router();
router.get("/config", protect, getSyncConfig);
router.put("/settings", protect, updateSettings);
router.get("/devices", protect, getDevices);
router.post("/devices", protect, addDevice);
router.get("/backups", protect, getBackups);
router.post("/backups", protect, triggerBackup);
router.post("/restore", protect, restoreBackup);
router.get("/conflicts", protect, getConflicts);
export default router;
