import React, { useState } from 'react';
import { ReturnInvoiceSelector } from '../../../frontend/src/pages/returns/ReturnInvoiceSelector';
import { ReturnItemGrid } from '../../../frontend/src/pages/returns/ReturnItemGrid';
import { ReturnSummary } from '../../../frontend/src/pages/returns/ReturnSummary';
import { ReturnedItemsList } from '../../../frontend/src/pages/returns/ReturnedItemsList';
import { Sale } from '../../types/sales';
import { SalesReturn as SalesReturnType, SalesReturnItem } from '../../types/salesReturn';
import { ArrowLeft, History } from 'lucide-react';
import { useSalesReturnManager } from '../../hooks/useSalesReturnManager';
import { useSelector } from 'react-redux';
import { RootState } from '../../store';

const SalesReturn = () => {
    // Steps: 'select-invoice' | 'return-items'
    const [step, setStep] = useState<'select-invoice' | 'return-items' | 'history'>('select-invoice');
    const { user } = useSelector((state: RootState) => state.auth);

    // State
    const [selectedInvoice, setSelectedInvoice] = useState<Sale | null>(null);
    const [returnItems, setReturnItems] = useState<SalesReturnItem[]>([]);
    const [refundMethod, setRefundMethod] = useState<SalesReturnType['refundMethod']>('cash');

    const { processReturn, returnsHistory, isProcessing } = useSalesReturnManager();

    const handleSelectInvoice = (invoice: Sale) => {
        setSelectedInvoice(invoice);
        setStep('return-items');
        setReturnItems([]); // Reset
    };

    const handleConfirmReturn = async () => {
        if (!selectedInvoice || returnItems.length === 0 || !user?.tenantId) return;

        const totalRefund = returnItems.reduce((acc, item) => acc + item.lineTotal, 0);

        const newReturn: SalesReturnType = {
            id: '', // Generated by DB
            tenantId: user.tenantId,
            branchId: selectedInvoice.branchId || '',
            invoiceId: selectedInvoice.id,
            customerId: selectedInvoice.customerId,
            customerName: selectedInvoice.customerName,
            returnDate: new Date().toISOString(),
            subtotal: totalRefund, // Assuming tax included in lineTotal for now
            taxAmount: 0,
            totalRefundAmount: totalRefund,
            status: 'completed',
            refundMethod: refundMethod,
            refundStatus: 'processed',
            items: returnItems,
            notes: '' // Add optional notes field in UI later
        };

        const result = await processReturn(newReturn);

        if (result.success) {
            setStep('history');
            setSelectedInvoice(null);
            setReturnItems([]);
        } else {
            console.error('Return failed', result.error);
        }
    };

    return (
        <div className="space-y-6 h-full flex flex-col animate-fade-in relative">
            {/* Header */}
            <div className="flex justify-between items-center mb-2">
                <div>
                    <h2 className="text-2xl font-bold text-slate-900 dark:text-white flex items-center gap-2">
                        Sales Return
                        <span className="px-2 py-0.5 bg-red-100 text-red-600 rounded text-xs font-black uppercase tracking-wider">Beta</span>
                    </h2>
                    <p className="text-slate-500 text-sm">Process refunds and manage returns</p>
                </div>

                <div className="flex gap-2">
                    {step !== 'history' && (
                        <button
                            onClick={() => setStep('history')}
                            className="px-4 py-2 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-slate-700 dark:text-white font-medium flex items-center gap-2 hover:bg-slate-50 transition-colors"
                        >
                            <History className="w-4 h-4" />
                            View History
                        </button>
                    )}
                    {step === 'history' && (
                        <button
                            onClick={() => setStep('select-invoice')}
                            className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-lg font-medium shadow-lg shadow-indigo-500/30 transition-all flex items-center gap-2"
                        >
                            + New Return
                        </button>
                    )}
                </div>
            </div>

            {/* Back Button during flow */}
            {step === 'return-items' && (
                <button
                    onClick={() => setStep('select-invoice')}
                    className="absolute top-0 right-0 hidden" // hidden for now, or place wisely
                >
                    Back
                </button>
            )}

            {/* Main Content Area */}
            <div className="flex-1 min-h-0">
                {step === 'history' && (
                    <ReturnedItemsList
                        returns={returnsHistory}
                        onViewDetails={(r) => console.log(r)}
                    />
                )}

                {step === 'select-invoice' && (
                    <div className="h-[600px]">
                        <ReturnInvoiceSelector onSelectInvoice={handleSelectInvoice} />
                    </div>
                )}

                {step === 'return-items' && selectedInvoice && (
                    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 h-full">
                        <div className="lg:col-span-2 space-y-4">
                            <div className="flex items-center gap-4 mb-2">
                                <button
                                    onClick={() => setStep('select-invoice')}
                                    className="p-2 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-full transition-colors"
                                >
                                    <ArrowLeft className="w-5 h-5 text-slate-500" />
                                </button>
                                <div>
                                    <h3 className="font-bold text-lg dark:text-white">Return for Invoice #{selectedInvoice.id.substring(0, 8)}</h3>
                                    <p className="text-sm text-slate-500">Select items and condition</p>
                                </div>
                            </div>

                            <ReturnItemGrid
                                invoice={selectedInvoice}
                                onItemsChange={setReturnItems}
                            />
                        </div>

                        <div className="lg:col-span-1">
                            <ReturnSummary
                                totalRefund={returnItems.reduce((acc, item) => acc + item.lineTotal, 0)}
                                itemsCount={returnItems.length}
                                refundMethod={refundMethod}
                                onMethodChange={setRefundMethod}
                                onConfirm={handleConfirmReturn}
                                isProcessing={isProcessing}
                            />
                        </div>
                    </div>
                )}
            </div>
        </div>
    );
};

export default SalesReturn;
