import { Router } from "express";
import { container } from "tsyringe";
import { InventoryController } from "../controllers/InventoryController.js";
import { CategoryController } from "../controllers/CategoryController.js";
import { protect } from '@smarterp/shared/middlewares/authMiddleware.js';
import { requirePermission } from '@smarterp/shared/middlewares/rbacMiddleware.js';
import { importLimiter } from '@smarterp/shared/middlewares/rateLimiter.js';
import { cacheMiddleware } from '@smarterp/shared/config/cache.js';
const router = Router();
const inventoryController = container.resolve(InventoryController);
const categoryController = new CategoryController();
router.get("/categories", protect, cacheMiddleware(3600), categoryController.getAllCategories);
router.post("/items", protect, inventoryController.addItem);
router.post("/import", protect, importLimiter, inventoryController.importItems);
router.get("/items", protect, cacheMiddleware(300), inventoryController.getAllItems);
router.get("/inventory-stats", protect, cacheMiddleware(300), inventoryController.getInventoryStats);
router.get("/low-stock", protect, cacheMiddleware(300), inventoryController.getLowStockItems);
router.get("/aging-reports", protect, cacheMiddleware(600), inventoryController.getStockAgingReport);
router.post("/aging-actions", protect, inventoryController.performAgingAction);
router.post("/batch-price-update", protect, inventoryController.batchPriceUpdate);
router.get("/reprint-queues", protect, inventoryController.getReprintQueue);
router.delete("/reprint-queues", protect, inventoryController.clearReprintQueue);
router.put("/bulk/category", protect, inventoryController.bulkUpdateCategory);
router.put("/bulk/stock", protect, inventoryController.bulkAdjustStock);
router.get("/:id", protect, inventoryController.getSingleItem);
router.post("/:id/movements", protect, inventoryController.recordMovement);
router.put("/:id", protect, 
//   auditUpdate("Item", "UPDATE_ITEM"),
inventoryController.updateItem);
router.delete("/batch", protect, requirePermission("delete:item"), inventoryController.deleteItemsBatch);
router.delete("/:id", protect, requirePermission("delete:item"), inventoryController.deleteItem);
router.post("/:id/duplicate", protect, inventoryController.duplicateItem);
router.patch("/:id/toggle-status", protect, inventoryController.toggleItemStatus);
router.get("/:id/history", protect, inventoryController.getItemStockHistory);
router.get("/:id/movements", protect, inventoryController.getItemStockHistory);
export default router;
