import React from 'react';
import { Database } from 'lucide-react';
import { formatDateTime, formatNumber, formatReportDate } from '@/utils/formatters';
import type { ReportDataSource } from '../config/reportRegistry';
import { ReportDisplayStatus, ReportStatusBadge } from './ReportStatusBadge';
import { dataSourceLabel } from './reportHelpers';
import type { ResolvedSource } from './reportHelpers';

export interface ReportAuditMetaProps {
    dataSource: ReportDataSource | null;
    resolvedSource?: ResolvedSource | null;
    /** Latest date covered by the data (e.g. the latest sale in the restored shop copy). */
    asOf?: string | null;
    /** When this screen last received the data. */
    refreshedAt?: Date | null;
    recordCount?: number | null;
    status: ReportDisplayStatus;
}

const Sep = () => <span className="hidden sm:inline text-slate-300 dark:text-slate-600" aria-hidden>|</span>;

/** Generated by the shell on every report, never hand-written per report. */
export const ReportAuditMeta: React.FC<ReportAuditMetaProps> = ({ dataSource, resolvedSource, asOf, refreshedAt, recordCount, status }) => (
    <footer className="pt-4 border-t border-slate-200 dark:border-slate-700 flex flex-col sm:flex-row sm:items-center justify-between gap-3 text-xs text-slate-500 dark:text-slate-400">
        <dl className="flex flex-col sm:flex-row sm:flex-wrap sm:items-center gap-x-3 gap-y-1">
            <div className="flex items-center gap-1.5">
                <Database className="w-3.5 h-3.5" aria-hidden />
                <dt>Data source:</dt>
                <dd className="font-bold text-slate-700 dark:text-slate-300">{dataSourceLabel(dataSource, resolvedSource)}</dd>
            </div>
            {asOf && (<><Sep /><div className="flex gap-1"><dt>Data as of:</dt><dd className="font-bold text-slate-700 dark:text-slate-300">{formatReportDate(asOf)}</dd></div></>)}
            {refreshedAt && (<><Sep /><div className="flex gap-1"><dt>Last refreshed:</dt><dd className="font-bold text-slate-700 dark:text-slate-300">{formatDateTime(refreshedAt)}</dd></div></>)}
            {recordCount !== undefined && recordCount !== null && (<><Sep /><div className="flex gap-1"><dt>Records:</dt><dd className="font-bold text-slate-700 dark:text-slate-300 tabular-nums">{formatNumber(recordCount)}</dd></div></>)}
            <Sep />
            <div><ReportStatusBadge status={status} /></div>
        </dl>
        <p className="shrink-0">All amounts in ₹ (INR)</p>
    </footer>
);
