export const customers = [
    {
        "id": "C001-TEN001",
        "tenant_id": "TEN001",
        "name": "Rajesh Kumar",
        "phone": "9876543210",
        "email": "rajesh.kumar@email.com",
        "address": "123, Main Street, Chennai",
        "outstanding_balance": 2316,
        "loyalty_points": 385,
        "sector": "Textiles",
        "creditBalance": 6672,
        "creditLimit": 10000,
        "lastPaymentDate": "2025-12-03",
        "riskScore": "HIGH"
    },
    {
        "id": "C002-TEN001",
        "tenant_id": "TEN001",
        "name": "Priya Sharma",
        "phone": "9876543211",
        "email": "priya.sharma@email.com",
        "address": "123, Main Street, Chennai",
        "outstanding_balance": 1964,
        "loyalty_points": 387,
        "sector": "Textiles",
        "creditBalance": 12423,
        "creditLimit": 15000,
        "lastPaymentDate": "2025-12-23",
        "riskScore": "MEDIUM"
    },
    {
        "id": "C003-TEN001",
        "tenant_id": "TEN001",
        "name": "Amit Patel",
        "phone": "9876543212",
        "email": "amit.patel@email.com",
        "address": "123, Main Street, Chennai",
        "outstanding_balance": 840,
        "loyalty_points": 47,
        "sector": "Textiles",
        "creditBalance": 8236,
        "creditLimit": 20000,
        "lastPaymentDate": "2025-11-19",
        "riskScore": "LOW"
    },
    {
        "id": "C004-TEN001",
        "tenant_id": "TEN001",
        "name": "Sunita Reddy",
        "phone": "9876543213",
        "email": "sunita.reddy@email.com",
        "address": "123, Main Street, Chennai",
        "outstanding_balance": 2035,
        "loyalty_points": 193,
        "sector": "Textiles",
        "creditBalance": 17886,
        "creditLimit": 25000,
        "lastPaymentDate": "2025-11-14",
        "riskScore": "HIGH"
    },
    {
        "id": "C005-TEN001",
        "tenant_id": "TEN001",
        "name": "Vikram Singh",
        "phone": "9876543214",
        "email": "vikram.singh@email.com",
        "address": "123, Main Street, Chennai",
        "outstanding_balance": 4599,
        "loyalty_points": 403,
        "sector": "Textiles",
        "creditBalance": 0,
        "creditLimit": 0,
        "lastPaymentDate": null,
        "riskScore": null
    },
    {
        "id": "C006-TEN001",
        "tenant_id": "TEN001",
        "name": "Meera Nair",
        "phone": "9876543215",
        "email": "meera.nair@email.com",
        "address": "123, Main Street, Chennai",
        "outstanding_balance": 222,
        "loyalty_points": 336,
        "sector": "Textiles",
        "creditBalance": 0,
        "creditLimit": 0,
        "lastPaymentDate": null,
        "riskScore": null
    },
    {
        "id": "C007-TEN001",
        "tenant_id": "TEN001",
        "name": "Karthik Iyer",
        "phone": "9876543216",
        "email": "karthik.iyer@email.com",
        "address": "123, Main Street, Chennai",
        "outstanding_balance": 2275,
        "loyalty_points": 372,
        "sector": "Textiles",
        "creditBalance": 0,
        "creditLimit": 0,
        "lastPaymentDate": null,
        "riskScore": null
    },
    {
        "id": "C008-TEN001",
        "tenant_id": "TEN001",
        "name": "Anjali Gupta",
        "phone": "9876543217",
        "email": "anjali.gupta@email.com",
        "address": "123, Main Street, Chennai",
        "outstanding_balance": 1965,
        "loyalty_points": 419,
        "sector": "Textiles",
        "creditBalance": 0,
        "creditLimit": 0,
        "lastPaymentDate": null,
        "riskScore": null
    },
    {
        "id": "C101-TEN002",
        "tenant_id": "TEN002",
        "name": "Ganesh Shop",
        "phone": "9876500001",
        "email": "ganesh.shop@email.com",
        "address": "123, Main Street, Salem",
        "outstanding_balance": 2347,
        "loyalty_points": 466,
        "sector": "FMCG",
        "creditBalance": 4475,
        "creditLimit": 10000,
        "lastPaymentDate": "2025-12-13",
        "riskScore": "HIGH"
    },
    {
        "id": "C102-TEN002",
        "tenant_id": "TEN002",
        "name": "Sri Lakshmi Store",
        "phone": "9876500002",
        "email": "sri.lakshmi store@email.com",
        "address": "123, Main Street, Salem",
        "outstanding_balance": 188,
        "loyalty_points": 25,
        "sector": "FMCG",
        "creditBalance": 9932,
        "creditLimit": 15000,
        "lastPaymentDate": "2026-01-02",
        "riskScore": "MEDIUM"
    },
    {
        "id": "C103-TEN002",
        "tenant_id": "TEN002",
        "name": "Balaji Mart",
        "phone": "9876500003",
        "email": "balaji.mart@email.com",
        "address": "123, Main Street, Salem",
        "outstanding_balance": 2484,
        "loyalty_points": 497,
        "sector": "FMCG",
        "creditBalance": 0,
        "creditLimit": 0,
        "lastPaymentDate": null,
        "riskScore": null
    },
    {
        "id": "C104-TEN002",
        "tenant_id": "TEN002",
        "name": "Murugan Traders",
        "phone": "9876500004",
        "email": "murugan.traders@email.com",
        "address": "123, Main Street, Salem",
        "outstanding_balance": 3204,
        "loyalty_points": 148,
        "sector": "FMCG",
        "creditBalance": 0,
        "creditLimit": 0,
        "lastPaymentDate": null,
        "riskScore": null
    },
    {
        "id": "C201-TEN003",
        "tenant_id": "TEN003",
        "name": "Tech Solutions Corp",
        "phone": "9876600001",
        "email": "tech.solutions corp@email.com",
        "address": "123, Main Street, Coimbatore",
        "outstanding_balance": 4040,
        "loyalty_points": 131,
        "sector": "Electronics",
        "creditBalance": 6046,
        "creditLimit": 10000,
        "lastPaymentDate": "2025-12-12",
        "riskScore": "HIGH"
    },
    {
        "id": "C202-TEN003",
        "tenant_id": "TEN003",
        "name": "Digital World Store",
        "phone": "9876600002",
        "email": "digital.world store@email.com",
        "address": "123, Main Street, Coimbatore",
        "outstanding_balance": 3240,
        "loyalty_points": 364,
        "sector": "Electronics",
        "creditBalance": 12649,
        "creditLimit": 15000,
        "lastPaymentDate": "2025-11-26",
        "riskScore": "MEDIUM"
    },
    {
        "id": "C203-TEN003",
        "tenant_id": "TEN003",
        "name": "Gadget Hub",
        "phone": "9876600003",
        "email": "gadget.hub@email.com",
        "address": "123, Main Street, Coimbatore",
        "outstanding_balance": 254,
        "loyalty_points": 102,
        "sector": "Electronics",
        "creditBalance": 0,
        "creditLimit": 0,
        "lastPaymentDate": null,
        "riskScore": null
    }
];
